server.port=8085
spring.application.name=investment-service

spring.datasource.url=jdbc:postgresql://localhost:5432/investment_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
