server.port=8083
spring.application.name=startup-service

spring.datasource.url=jdbc:postgresql://localhost:5432/startup_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

resilience4j.circuitbreaker.instances.investmentService.sliding-window-size=10
resilience4j.circuitbreaker.instances.investmentService.failure-rate-threshold=50
