server.port=8084
spring.application.name=team-service

spring.datasource.url=jdbc:postgresql://localhost:5432/team_service_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

resilience4j.circuitbreaker.instances.userService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
